SourceCode/backend/colabTeam_web/api/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from .views import PostViewSet

router = SimpleRouter()
router.register("", PostViewSet, basename="post")

app_name = "api"

urlpatterns = [
    path("posts/", include(router.urls)),
    path("user/", include("registration_app.api.urls")),
]

SourceCode/backend/colabTeam_web/colabTeam_web/urls.py
# colabTeam_web/urls.py

from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home_app.urls")),
    path("user/", include("registration_app.urls")),
    path("api/v1/", include("api.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SourceCode/backend/colabTeam_web/home_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "home_app"

urlpatterns = [
    path("", views.HomeView, name="home"),
    path("add_post", views.add_post, name="add_post"),
    path("posts", views.posts, name="posts"),
    path("post/<int:post_id>/", views.post_detail, name="post_detail"),
    path(
        "reset-password",
        auth_views.PasswordResetView.as_view(
            template_name="registration/password_reset/password_reset_form.html",
            html_email_template_name="registration/custom_password_reset_email.html",
        ),
        name="password_reset",
    ),
    path(
        "reset-password/done",
        auth_views.PasswordResetDoneView.as_view(
            template_name="registration/password_reset/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>[0-9A-Za-z]+)-<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="registration/password_reset/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

SourceCode/backend/colabTeam_web/registration_app/urls.py
from django.urls import path

from . import views

# Define the namespace for the URL patterns for this app.
app_name = "registration_app"

# Define URL patterns for various views in the 'registration_app' app.
urlpatterns = [
    path("login", views.login_user, name="login"),  # URL for user login
    path("register", views.register_user, name="register"),  # URL for user registration
    path("logout", views.logout_user, name="logout"),  # URL for user logout
    path(
        "token/", views.token_send, name="token"
    ),  # URL for sending tokens (corrected typo)
    path("success/", views.success, name="success"),  # URL for success page
    path(
        "verify/<auth_token>",
        views.verify_user,  # type: ignore
        name="verify",
    ),  # URL for verifying user
    path("profile/", views.profilePage, name="profile"),  # URL for error page
    path(
        "edit_profile/", views.profileUpdatePage, name="edit_profile"
    ),  # URL for error page
    path("error/", views.error_page, name="error"),  # URL for error page
]

SourceCode/backend/colabTeam_web/templates/profile/edit_profile.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'profile/css/home.css' %}">
    <link rel="stylesheet" href="{% static 'profile/css/profile.css' %}">

    <title>Profile</title>
  </head>
  <body>

    <header>
        <nav class="navbar">
            <a href="home.html" class="logo">Profile</a>
                
        </nav>
    </header>

    <main class="main-container" style="box-shadow: rgba(0, 0, 0, 0.3) 0px 19px 38px, rgba(0, 0, 0, 0.22) 0px 15px 12px;">
            <form class = 'container' method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="profile-photo-container profile-photo-form-container">
                    <p class="profile-page-heading">Edit your profile</p>
                    <img src="{{ user.profile.profilePic.url}}" alt="user-image" width="" srcset="">
                </div>
            

                <div class="user-content-container user-profile-form-container">
                    <ul>
                        <li class="name">
                            
                            {{ form }}
                        </li>
                    </ul>
                    <button type="submit" class="profile-save-button"> Save </button>
                </div>
            </form>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script>

    var id_name = document.getElementById('id_name')
    var id_title = document.getElementById('id_title')
    var id_desc = document.getElementById('id_desc')
    id_name.placeholder = 'Your Name'
    id_title.placeholder = 'Your Title'
    id_desc.placeholder = 'Description'

    </script>
  </body>
</html>

SourceCode/backend/colabTeam_web/templates/profile/profile.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'profile/css/home.css' %}">

    <title>Home</title>
  </head>
  <body>
    <header>
        <nav class="navbar">
            <p class="logo">Profile</p>
            {% if user.is_authenticated %}
              <a href='{% url 'home_app:home' %}' ><button class="btn btn-primary m-1">Home</button></a>
            {% else %}
            {% endif %}
        </nav>
    </header>

    <script>
        var cross = document.getElementById('cross')
        cross.addEventListener('click', ()=> {
            document.getElementsByClassName('notification-container')[0].style.display = 'none';
        })

    </script>


    <main class="main-container" style="box-shadow: rgba(0, 0, 0, 0.3) 0px 19px 38px, rgba(0, 0, 0, 0.22) 0px 15px 12px;">
        <div class="container">
            <div class="profile-photo-container">
                <img src="{{ user.profile.profilePic.url }}" alt="User Image" width="100px" srcset="">
            </div>
    
            <div class="user-content-container">
                <p class="username">Username: {{ user.profile.user }}</p>
                <p class="user-title">Name: {{ user.profile.fName }} {{ user.profile.lName }}</p>
                <p id="bio" class="user-desc">{{ user.profile.bioText }}</p>
                <div class="profile-edit-link-container">
                    <a href="{% url 'registration_app:edit_profile' %}">Edit</a>
                </div>
            </div>
        </div>
    </main>
    
    

    <div class="row row-cols-1 row-cols-md-3 g-4 container">
        {% if user_posts %}
                {% for post in user_posts %}
        <div class="col">
          <div class="card h-100">
            <img src="https://wpklik.com/wp-content/uploads/2018/10/wordpress-blog-post.jpg" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">{{ post.title }}</h5>
              <p class="card-text">{{ post.description|truncatewords:100 }}
              </p>
              <a href="{% url 'home_app:post_detail' post_id=post.pk %}"><button type="button" class="btn btn-secondary">Update</button></a>
              <a href="{% url 'home_app:post_detail' post_id=post.pk %}"><button type="button" class="btn btn-outline-warning">More →</button></a>
            </div>
          </div>
        </div>
        {% endfor %}
            {% else %}
            <center>
                No posts to display
            </center>
            {% endif %}
      </div>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>