SourceCode/backend/colabTeam_web/api/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from .views import PostViewSet

router = SimpleRouter()
router.register("", PostViewSet, basename="post")

app_name = "api"

urlpatterns = [
    path("posts/", include(router.urls)),
    path("user/", include("registration_app.api.urls")),
]

SourceCode/backend/colabTeam_web/colabTeam_web/urls.py
# colabTeam_web/urls.py

from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home_app.urls")),
    path("user/", include("registration_app.urls")),
    path("api/v1/", include("api.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SourceCode/backend/colabTeam_web/home_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "home_app"

urlpatterns = [
    path("", views.HomeView, name="home"),
    path("add_post", views.add_post, name="add_post"),
    path("posts", views.posts, name="posts"),
    path("post/<int:post_id>/", views.post_detail, name="post_detail"),
    path(
        "reset-password",
        auth_views.PasswordResetView.as_view(
            template_name="registration/password_reset/password_reset_form.html",
            html_email_template_name="registration/custom_password_reset_email.html",
        ),
        name="password_reset",
    ),
    path(
        "reset-password/done",
        auth_views.PasswordResetDoneView.as_view(
            template_name="registration/password_reset/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>[0-9A-Za-z]+)-<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="registration/password_reset/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

SourceCode/backend/colabTeam_web/registration_app/urls.py
from django.urls import path

from . import views

# Define the namespace for the URL patterns for this app.
app_name = "registration_app"

# Define URL patterns for various views in the 'registration_app' app.
urlpatterns = [
    path("login", views.login_user, name="login"),  # URL for user login
    path("register", views.register_user, name="register"),  # URL for user registration
    path("logout", views.logout_user, name="logout"),  # URL for user logout
    path(
        "token/", views.token_send, name="token"
    ),  # URL for sending tokens (corrected typo)
    path("success/", views.success, name="success"),  # URL for success page
    path(
        "verify/<auth_token>",
        views.verify_user,  # type: ignore
        name="verify",
    ),  # URL for verifying user
    path("profile/", views.profilePage, name="profile"),  # URL for error page
    path(
        "edit_profile/", views.profileUpdatePage, name="edit_profile"
    ),  # URL for error page
    path("error/", views.error_page, name="error"),  # URL for error page
]

SourceCode/backend/colabTeam_web/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>COLAB TEAM |{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home_app:home' %}">COLAB TEAM</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home_app:home' %}">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a href="{% url 'home_app:add_post' %}" class="nav-link" ><button class=" btn btn-primary ">New Post</button></a>
              </li>
              {% endif %}
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            {% if user.is_authenticated %}
              <a href='{% url 'registration_app:logout' %}' ><button class="btn btn-primary m-1">Logout</button></a>
              <a href='{% url 'registration_app:profile' %}' ><button class="btn btn-outline-primary m-1">Profile</button></a>
            {% else %}
              <a href='{% url 'registration_app:login' %}' ><button class="btn btn-primary m-1">Login</button></a>
              <a href='{% url 'registration_app:register' %}' ><button class="btn btn-dark m-1">Register</button></a>
            {% endif %}
          </div>
        </div>
      </nav>
      <div class="main">
        {% block content %}{% endblock %}
      </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

SourceCode/backend/colabTeam_web/templates/index.html
{% extends "base.html" %}
{% block title %}{{ post.title }} Home{% endblock %}

{% block content %}
      <br>
      <br>
      <div class="main container">
        <div class="row row-cols-1 row-cols-md-2 g-4">
          <div class="col">
            <div class="card">
              <img src="https://www.dignited.com/wp-content/uploads/2023/02/IDE.jpeg" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">All Project Posts</h5>
                <p class="card-text">See all project requests made by others.</p>
                <a href="{% url 'home_app:posts' %}"><button type="button" class="btn btn-outline-warning">View →</button>
                  </a>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card">
              <img src="https://www.elegantthemes.com/blog/wp-content/uploads/2021/04/000-WordPress-Posts.png" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Add New</h5>
                <p class="card-text">Put your request for others to see.</p>
                {% if user.is_authenticated %}
                <a href="{% url 'home_app:add_post' %}"><button type="button" class="btn btn-outline-warning">Add →</button>
                  {% else %}
                  <a href="{% url 'registration_app:login' %}"><button type="button" class="btn btn-outline-danger">Please Login 🔒</button>
                  {% endif %}
                </a>
              </div>
            </div>
          </div>

      </div>
      {% endblock %}